debug:	lab9_1/Lab9_1.s
	as -g -o lab9_1/Lab9_1.o lab9_1/Lab9_1.s
	gcc -o lab9_1/Lab9_1 lab9_1/Lab9_1.o
	gdb lab9_1/Lab9_1

Lab9_2: lab9_2/Lab9_2.s
	as -g -o lab9_2/Lab9_2.o lab9_2/Lab9_2.s
	gcc -o lab9_2/Lab9_2 lab9_2/Lab9_2.o
	gdb lab9_2/Lab9_2

Lab9_3: lab9_3/Lab9_3.s
	as -g -o lab9_3/Lab9_3.o lab9_3/Lab9_3.s
	gcc -o lab9_3/Lab9_3 lab9_3/Lab9_3.o
	gdb lab9_3/Lab9_3

Lab9_4: lab9_4/main.c
	gcc -o lab9_4/Lab9_4 lab9_4/main.c lab9_4/add_s.s
	gdb lab9_4/Lab9_4
