Lab8_1: Lab8_1.s
	gcc -o Lab8_1 Lab8_1.s
Lab8_2: Lab8_2.s
	gcc -o Lab8_2 Lab8_2.s
Lab8_3: Lab8_3.s
	gcc -o Lab8_3 Lab8_3.s
Lab8_4: Lab8_4.s
	gcc -o Lab8_4 Lab8_4.s
Lab8_5: Lab8_5.s
	gcc -o Lab8_5 Lab8_5.s
Lab8_6: Lab8_6.s
	gcc -o Lab8_6 Lab8_6.s

